from django.contrib import admin

from .models import DASMatriculeExo, DASEXOModel, DASDetail, DASModel, DAS, Situation, TableLiasseFiscale, LiasseFiscale, Task, Work, Benefit, BenefitLink,Claim,VATRequested,BenefitRequested, Period, BenefitItem, Account, Exercice,TaxReturn, CotisationMinimal, AccountBis, ImpotSociete, BaremeImpot

admin.site.register(Work)
admin.site.register(Task)
admin.site.register(Benefit)
admin.site.register(BenefitLink)
admin.site.register(Claim)
admin.site.register(VATRequested)
admin.site.register(BenefitRequested)
admin.site.register(Period)
admin.site.register(BenefitItem)
admin.site.register(Account)
admin.site.register(AccountBis)
admin.site.register(Exercice)
admin.site.register(Situation)
admin.site.register(TaxReturn)
admin.site.register(CotisationMinimal)
admin.site.register(ImpotSociete)
admin.site.register(BaremeImpot)
admin.site.register(TableLiasseFiscale)
admin.site.register(LiasseFiscale)
admin.site.register(DASDetail)
admin.site.register(DASModel)
admin.site.register(DAS)
admin.site.register(DASEXOModel)
admin.site.register(DASMatriculeExo)