# Generated by Django 3.2.4 on 2021-11-04 08:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ordres', '0007_lettremission_nothosted'),
        ('accounts', '0003_auto_20210720_1534'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='validator',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True, verbose_name='Active sur le dossier')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date création')),
                ('lettremission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ordres.lettremission', verbose_name='Mission')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile', verbose_name='Manager')),
            ],
            options={
                'unique_together': {('user', 'lettremission')},
            },
        ),
    ]
