# Generated by Django 3.2.4 on 2021-11-16 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_auto_20211115_1230'),
        ('accounts', '0004_auto_20211104_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='office',
            field=models.ForeignKey(default=3, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.office', verbose_name='Cabinet'),
        ),
    ]
