# Generated by Django 3.2.4 on 2021-11-17 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordres', '0008_alter_lettremissionlink_lettremission'),
        ('customers', '0014_auto_20211117_1714'),
        ('accounts', '0005_profile_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='lettremission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ordres.lettremission', verbose_name='Mission'),
        ),
        migrations.AlterField(
            model_name='portefolio',
            name='lettremission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ordres.lettremission', verbose_name='Mission'),
        ),
        migrations.AlterField(
            model_name='portefolio',
            name='rolecollaborateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.scope', verbose_name='En charge de'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='office',
            field=models.ForeignKey(default=3, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.office', verbose_name='Cabinet'),
        ),
        migrations.AlterField(
            model_name='pwsafe',
            name='lettremission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ordres.lettremission', verbose_name='Mission'),
        ),
        migrations.AlterField(
            model_name='validator',
            name='lettremission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ordres.lettremission', verbose_name='Mission'),
        ),
    ]
