# Generated by Django 3.2.4 on 2021-12-02 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0015_alter_office_company'),
        ('accounts', '0006_auto_20211117_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='office',
            field=models.ForeignKey(default=3, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.office', verbose_name='Cabinet'),
        ),
    ]
