# Generated by Django 3.2.4 on 2021-10-29 17:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0019_rename_baremeis_baremeimpot'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountLead',
            fields=[
                ('code_account', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Code Post / Compte')),
                ('name_account', models.CharField(max_length=100, verbose_name='Libellé du Compte')),
                ('level', models.IntegerField(choices=[(0, 'Rubrique'), (1, 'Poste'), (2, 'Compte'), (3, 'Sous-Compte')], default=2, verbose_name='Niveau du Compte')),
                ('sens', models.IntegerField(choices=[(0, 'Débit'), (1, 'Crédit')], verbose_name='Sens')),
                ('nature', models.IntegerField(choices=[(0, 'Bilan'), (1, 'CPC')], verbose_name='Nature')),
            ],
        ),
        migrations.CreateModel(
            name='SectionModel',
            fields=[
                ('code_section', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='Code Section')),
                ('name_section', models.CharField(max_length=100, verbose_name='Nom Section')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('date_generation', models.DateField(auto_created=True, null=True, verbose_name='Date')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audits.sectionmodel', verbose_name='Section')),
                ('situation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.situation', verbose_name='Situation')),
            ],
            options={
                'unique_together': {('situation', 'section')},
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xRef', models.CharField(blank=True, max_length=10, null=True, verbose_name='X-Référence')),
                ('data_n', models.FloatField(default=0, null=True, verbose_name='Valeur N')),
                ('data_n1', models.FloatField(default=0, null=True, verbose_name='Valeur N-1')),
                ('data_delta', models.FloatField(default=0, null=True, verbose_name='Variation')),
                ('data_delta_pc', models.FloatField(default=0, null=True, verbose_name='Pourcentage')),
                ('code_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audits.accountlead', verbose_name='Code Post / Compte')),
            ],
        ),
        migrations.CreateModel(
            name='GLVersion',
            fields=[
                ('date_edition', models.DateField(auto_created=True, null=True, verbose_name='Date Edition')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('closing', models.BooleanField(default=False, verbose_name='Version Définitive ?')),
                ('situation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.situation', verbose_name='Exercice')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journal', models.CharField(max_length=10, verbose_name='Journal')),
                ('num_piece', models.CharField(blank=True, max_length=10, null=True, verbose_name='Numéro Pièce')),
                ('date_entry', models.DateField(verbose_name='Date Ecriture')),
                ('account', models.CharField(max_length=14, verbose_name='Compte')),
                ('designation', models.CharField(blank=True, max_length=200, null=True, verbose_name='Désignation')),
                ('debit', models.FloatField(blank=True, null=True, verbose_name='Débit')),
                ('credit', models.FloatField(blank=True, null=True, verbose_name='Crédit')),
                ('reference', models.CharField(blank=True, max_length=20, null=True, verbose_name='Référence')),
                ('lettrage', models.CharField(blank=True, max_length=20, null=True, verbose_name='Lettrage')),
                ('glversion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audits.glversion', verbose_name='Grand Livre')),
            ],
        ),
        migrations.CreateModel(
            name='Conclusion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conclusion', models.TextField(blank=True, null=True, verbose_name='Conclusion')),
                ('statut', models.IntegerField(choices=[(0, 'En Rédaction'), (1, 'Traitée'), (2, 'Validée'), (3, 'Non-validée'), (4, 'Non Applicable')], default=0, verbose_name='Statut')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audits.section', verbose_name='Section')),
            ],
        ),
        migrations.AddField(
            model_name='accountlead',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audits.section', verbose_name='Section'),
        ),
    ]
