# Generated by Django 3.2.4 on 2021-10-30 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountlead',
            name='ordre',
            field=models.IntegerField(null=True, verbose_name='Ordre'),
        ),
        migrations.AddField(
            model_name='lead',
            name='auto_genre',
            field=models.BooleanField(default=False, verbose_name='Compte Auto-Généré ?'),
        ),
        migrations.AddField(
            model_name='lead',
            name='ordre',
            field=models.IntegerField(null=True, verbose_name='Ordre'),
        ),
    ]
