# Generated by Django 3.2.4 on 2021-10-30 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0002_auto_20211030_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='audits.section', verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='section',
            name='statut',
            field=models.IntegerField(choices=[(0, 'En Rédaction'), (1, 'Traitée'), (2, 'Validée'), (3, 'Non-validée'), (4, 'Non Applicable')], default=0, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='section',
            name='supervised',
            field=models.BooleanField(default=False, verbose_name='Supervisé'),
        ),
        migrations.AlterField(
            model_name='accountlead',
            name='level',
            field=models.IntegerField(choices=[(1, 'Calsse'), (2, 'Rubrique'), (3, 'Poste'), (4, 'Compte'), (5, 'Sous-Compte')], default=4, verbose_name='Niveau du Compte'),
        ),
    ]
