# Generated by Django 3.2.4 on 2021-10-30 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0004_alter_accountlead_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountlead',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='audits.sectionmodel', verbose_name='Section'),
        ),
    ]
