# Generated by Django 3.2.4 on 2021-10-31 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0006_lead_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='level',
        ),
    ]
