# Generated by Django 3.2.4 on 2021-11-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0007_remove_lead_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glversion',
            name='date_edition',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Date Edition'),
        ),
        migrations.AlterField(
            model_name='section',
            name='date_generation',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Date'),
        ),
    ]
