# Generated by Django 3.2.4 on 2021-11-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0008_auto_20211101_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='date_generation',
            field=models.DateField(null=True, verbose_name='Date'),
        ),
    ]
