# Generated by Django 3.2.4 on 2021-11-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0009_alter_section_date_generation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conclusion',
            name='conclusion',
            field=models.TextField(blank=True, null=True, verbose_name='Texte'),
        ),
    ]
