# Generated by Django 3.2.4 on 2021-12-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0011_conclusion_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionmodel',
            name='type',
            field=models.IntegerField(choices=[(0, 'CPC'), (1, 'Bilan')], default=0, verbose_name='Type de Section'),
        ),
    ]
