# Generated by Django 3.2.4 on 2021-07-31 12:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ordres', '0002_alter_lettremission_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocModel',
            fields=[
                ('code_docmodel', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Code')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du Modèle')),
            ],
        ),
        migrations.CreateModel(
            name='SocialDoc',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_doc', models.DateTimeField(auto_now_add=True, verbose_name='Date Document')),
                ('lettremission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ordres.lettremission', verbose_name='Lettre de Mission')),
            ],
        ),
        migrations.CreateModel(
            name='DocModelWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre_parag', models.IntegerField(null=True, verbose_name='Ordre Paragraphe')),
                ('type_parag', models.IntegerField(choices=[(1, 'Titre'), (2, 'Paragraphe'), (3, 'En-tête'), (4, 'Bas de Page')], default=2, null=True, verbose_name='Type Paragraphe')),
                ('sort_parag', models.IntegerField(blank=True, null=True, verbose_name='Classement Titre (1 à 7)')),
                ('size_font', models.DecimalField(decimal_places=2, default=11, max_digits=4, null=True, verbose_name='Taille du caractère')),
                ('space_after_parag', models.DecimalField(decimal_places=2, default=3, max_digits=4, null=True, verbose_name='Espace après')),
                ('space_befor_parag', models.DecimalField(decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Espace avant')),
                ('alignment_parag', models.IntegerField(choices=[(1, 'Titre'), (2, 'Paragraphe'), (3, 'En-tête'), (4, 'Bas de Page')], default=2, null=True, verbose_name='Alignement Paragraphe')),
                ('ident_first_ligne', models.DecimalField(decimal_places=2, default=0, max_digits=4, null=True, verbose_name='Retrait Première Ligne')),
                ('code_docmodel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='editions.docmodel', verbose_name='Nom Modèle')),
            ],
        ),
    ]
