# Generated by Django 3.2.4 on 2021-08-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0002_auto_20210731_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='docmodelword',
            name='texte',
            field=models.TextField(blank=True, null=True, verbose_name='Text'),
        ),
    ]
