# Generated by Django 3.2.4 on 2021-08-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0003_docmodelword_texte'),
    ]

    operations = [
        migrations.AddField(
            model_name='docmodel',
            name='footer',
            field=models.BooleanField(default=False, verbose_name='Pied de Page'),
        ),
        migrations.AddField(
            model_name='docmodel',
            name='header',
            field=models.BooleanField(default=False, verbose_name='Entête de Page'),
        ),
        migrations.AlterField(
            model_name='docmodelword',
            name='size_font',
            field=models.DecimalField(decimal_places=2, default=12, max_digits=4, null=True, verbose_name='Taille du caractère'),
        ),
        migrations.AlterField(
            model_name='docmodelword',
            name='sort_parag',
            field=models.IntegerField(blank=True, null=True, verbose_name='Classement Titre (0 à 6)'),
        ),
        migrations.AlterField(
            model_name='docmodelword',
            name='space_after_parag',
            field=models.DecimalField(decimal_places=2, default=6, max_digits=4, null=True, verbose_name='Espace après'),
        ),
    ]
