# Generated by Django 3.2.4 on 2021-08-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0006_alter_docmodel_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='docmodelword',
            name='italic_font',
            field=models.BooleanField(default=False, verbose_name='Italic'),
        ),
        migrations.AlterField(
            model_name='docmodelword',
            name='alignment_parag',
            field=models.IntegerField(choices=[(1, 'Titre'), (2, 'Paragraphe'), (3, 'Phrase / Mot')], default=4, null=True, verbose_name='Alignement Paragraphe'),
        ),
        migrations.AlterField(
            model_name='docmodelword',
            name='space_befor_parag',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=4, null=True, verbose_name='Espace avant'),
        ),
        migrations.AlterField(
            model_name='docmodelword',
            name='type_parag',
            field=models.IntegerField(choices=[(1, 'Titre'), (2, 'Paragraphe'), (3, 'Phrase / Mot')], default=2, null=True, verbose_name='Type Paragraphe'),
        ),
    ]
