# Generated by Django 3.2.4 on 2021-08-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editions', '0008_alter_docmodelword_alignment_parag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docmodelword',
            name='alignment_parag',
            field=models.CharField(choices=[('right', 'Droite'), ('center', 'Centre'), ('left', 'Gauche'), ('justify', 'Justifié')], default=4, max_length=10, null=True, verbose_name='Alignement Paragraphe'),
        ),
    ]
