# Generated by Django 3.2.4 on 2021-11-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_companytemps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companytemps',
            name='database',
        ),
        migrations.AddField(
            model_name='companytemps',
            name='codedb',
            field=models.CharField(max_length=3, null=True, verbose_name='Code Base Donnée'),
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='codedb',
            field=models.CharField(max_length=3, null=True, verbose_name='Code Base Donnée'),
        ),
    ]
