# Generated by Django 3.2.4 on 2021-11-17 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0013_auto_20211115_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companytemps',
            old_name='insert',
            new_name='exclude',
        ),
        migrations.AlterField(
            model_name='bankacount',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.company'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.company', verbose_name='Raison Sociale'),
        ),
        migrations.AlterField(
            model_name='office',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.company'),
        ),
        migrations.AlterField(
            model_name='representative',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.company', verbose_name='Raison Sociale'),
        ),
        migrations.AlterField(
            model_name='representativecompany',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.company', verbose_name='Raison Sociale'),
        ),
        migrations.AlterField(
            model_name='shareholder',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.company', verbose_name='Raison Sociale'),
        ),
        migrations.AlterField(
            model_name='shareholdercompany',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.company', verbose_name='Société Actionnaire'),
        ),
    ]
