# Generated by Django 3.2.4 on 2021-12-02 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0014_auto_20211117_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.company'),
        ),
    ]
