# Generated by Django 3.2.4 on 2021-09-13 16:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ordres', '0006_outlayitem_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('code_benefit', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='Code')),
                ('name', models.CharField(max_length=200, verbose_name='Particularité')),
            ],
        ),
        migrations.CreateModel(
            name='BenefitLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lettremission', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ordres.lettremission', verbose_name='Lettre de Mission')),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.CharField(max_length=6, unique=True, verbose_name='Période')),
                ('echeance', models.DateField(verbose_name='Echéance')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('code_task', models.CharField(max_length=3, primary_key=True, serialize=False, unique=True, verbose_name='Code Tâche')),
                ('name', models.CharField(max_length=150, verbose_name='Designation de la Tâche')),
                ('category', models.IntegerField(choices=[(1, 'TVA'), (2, 'IS'), (3, 'IR'), (4, 'Taxe'), (5, 'Cotisation'), (6, 'Rapport')], verbose_name='Catégorie')),
                ('to_add', models.IntegerField(choices=[(1, 'Day'), (2, 'Month'), (3, 'Year')], null=True, verbose_name='Ajouter à la Date')),
                ('numbre_add', models.IntegerField(null=True, verbose_name='Nombre à rajouter')),
                ('frequency', models.IntegerField(choices=[(1, 'Unique'), (2, 'Mois'), (3, 'Trim'), (4, 'Sems'), (5, 'Annuel')], null=True, verbose_name='Ajouter à la Date')),
                ('year_civil', models.BooleanField(default=False, null=True, verbose_name='Année Civile ?')),
                ('repeted', models.BooleanField(default=False, null=True, verbose_name='Récurrent ?')),
                ('specific', models.BooleanField(default=False, null=True, verbose_name='Spécifique ?')),
                ('persontype', models.IntegerField(choices=[(1, 'Société Commerciale'), (2, 'Entreprise Personnelle'), (3, 'Association'), (5, 'Commun')], null=True, verbose_name='Type de la Personne')),
                ('code_benefit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.benefit', verbose_name='Particularité')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_limit', models.DateField(verbose_name='Date Limite')),
                ('value', models.FloatField(default=0, null=True, verbose_name='Valeur')),
                ('proof', models.CharField(blank=True, max_length=200, null=True, verbose_name='N° Quittance')),
                ('statut', models.IntegerField(choices=[(0, 'En Cours'), (1, 'Traitée'), (2, 'Validée'), (3, 'Non-validée'), (4, 'Non Applicable')], default=0, verbose_name='Statut')),
                ('file', models.FileField(blank=True, upload_to='files/tasks/', verbose_name='Joindre Quittance')),
                ('supervised', models.BooleanField(default=False, verbose_name='Supervisé')),
                ('lettremission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ordres.lettremission', verbose_name='Lettre de Mission')),
                ('period', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.period', verbose_name='Echéance')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.task', verbose_name='Job to do')),
            ],
            options={
                'unique_together': {('period', 'lettremission', 'task')},
            },
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('objet', models.CharField(max_length=200, null=True, verbose_name='Objet de la réclamation')),
                ('date_start', models.DateField(auto_now_add=True, verbose_name='Date de la réclamation')),
                ('statut', models.IntegerField(choices=[(0, 'En Cours'), (1, 'Déposée'), (2, 'Accordée'), (3, 'Rejetée'), (4, 'Annulée')], default=0, verbose_name='Statut')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='Date de clôture')),
                ('complement', models.TextField(null=True, verbose_name='Commentaire')),
                ('invoiced', models.BooleanField(default=False, verbose_name='Facturable ?')),
                ('lettremission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ordres.lettremission', verbose_name='Lettre de Mission')),
            ],
        ),
        migrations.CreateModel(
            name='BenefitRequested',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amountrequested', models.FloatField(null=True, verbose_name='Mondant Demandé')),
                ('amountreceived', models.FloatField(null=True, verbose_name='Mondant Remboursé')),
                ('statut', models.IntegerField(choices=[(0, 'En Cours'), (1, 'Traitée'), (2, 'Validée'), (3, 'Non Applicable')], default=0, verbose_name='Statut')),
                ('complement', models.CharField(max_length=200, null=True, verbose_name='Complément')),
                ('worklink', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.work', verbose_name='Référence de la tâche')),
            ],
        ),
        migrations.CreateModel(
            name='VATRequested',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField(verbose_name='Exercice')),
                ('month', models.IntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], verbose_name='Mois')),
                ('amountrequested', models.FloatField(null=True, verbose_name='Mondant Demandé')),
                ('amountreceived', models.FloatField(null=True, verbose_name='Mondant Remboursé')),
                ('statut', models.IntegerField(choices=[(0, 'En Cours'), (1, 'Traitée'), (2, 'Validée'), (3, 'Non Applicable')], default=0, verbose_name='Statut')),
                ('complement', models.CharField(max_length=200, null=True, verbose_name='Complément')),
                ('benefitlink', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.benefitlink', verbose_name='Objet de la demande')),
                ('lettremission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ordres.lettremission', verbose_name='Lettre de Mission')),
            ],
            options={
                'unique_together': {('lettremission', 'benefitlink')},
            },
        ),
        migrations.CreateModel(
            name='BenefitItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True, verbose_name='Active ?')),
                ('date_start', models.DateField(null=True, verbose_name='Date début')),
                ('benefitlink', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.benefitlink', verbose_name='Lettre de Mission')),
                ('code_benefit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.benefit', verbose_name='Particularité')),
            ],
            options={
                'unique_together': {('benefitlink', 'code_benefit')},
            },
        ),
    ]
