# Generated by Django 3.2.4 on 2021-09-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='frequency',
            field=models.IntegerField(choices=[(1, 'Unique'), (2, 'Mois'), (3, 'Trim'), (4, 'Sems'), (5, 'Annuel')], null=True, verbose_name='Fréquence'),
        ),
        migrations.AlterField(
            model_name='task',
            name='persontype',
            field=models.IntegerField(choices=[(1, 'Société Commerciale'), (2, 'Entreprise Personnelle'), (3, 'Association'), (4, 'Particulier'), (5, 'Commun')], null=True, verbose_name='Type de la Personne'),
        ),
    ]
