# Generated by Django 3.2.4 on 2021-09-13 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20210913_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='code_benefit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.benefit', verbose_name='Particularité'),
        ),
    ]
