# Generated by Django 3.2.4 on 2021-09-16 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20210914_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.period', verbose_name='Echéance'),
        ),
    ]
