# Generated by Django 3.2.4 on 2021-09-27 14:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ordres', '0007_lettremission_nothosted'),
        ('tasks', '0007_alter_benefititem_frequency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('code_account', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Code Post / Compte')),
                ('name_account', models.CharField(max_length=100, verbose_name='Libellé du Compte')),
                ('deduc_reint', models.IntegerField(choices=[(0, 'Réintégration'), (1, 'Déduction')], default=0, verbose_name='Sens')),
                ('taxreturn', models.IntegerField(blank=True, choices=[(0, 'Commun'), (1, 'Résultat Fiscal'), (2, 'Imputation Déficites'), (3, 'Déficites Reportables'), (4, 'Déclaration')], default=0, verbose_name='Rubrique Déclaration Fiscal')),
                ('sens', models.IntegerField(choices=[(0, 'Débit'), (1, 'Crédit')], verbose_name='Sens')),
                ('account_lower', models.CharField(max_length=10, verbose_name='Compte Inférieure')),
                ('account_upper', models.CharField(max_length=10, verbose_name='Compte Supérieure')),
                ('exercice', models.IntegerField(choices=[(0, 'Exercice N (en Cours)'), (1, 'Exercice N-1'), (2, 'Exercice N-2'), (3, 'Exercice N-3'), (4, 'Exercice N-4')], default=0, verbose_name='Quel Exercice ?')),
                ('sql', models.IntegerField(choices=[(0, 'BETWEEN'), (1, 'LIKE')], default=0, verbose_name='SQL ?')),
            ],
        ),
        migrations.CreateModel(
            name='Exercice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exercice', models.CharField(max_length=4, unique=True, verbose_name='Exercice')),
                ('date_creation', models.DateField(auto_now_add=True, verbose_name='Date')),
            ],
        ),
        migrations.CreateModel(
            name='Situation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_start', models.DateField(verbose_name='Date début')),
                ('date_closing', models.DateField(verbose_name='Date clôture')),
                ('numbre_month', models.IntegerField(verbose_name='Nombre de mois')),
                ('date_declaration', models.DateField(verbose_name='Date limite déclaration')),
                ('date_ago', models.DateField(verbose_name='Date limite AGO')),
                ('statut', models.IntegerField(choices=[(0, 'En Cours'), (1, 'Traitée'), (2, 'Validée'), (3, 'Non-validée'), (4, 'Non Applicable')], default=0, verbose_name='Statut')),
                ('supervised', models.BooleanField(default=False, verbose_name='Supervisé')),
                ('exercice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.exercice', verbose_name='Exercice')),
                ('lettremission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ordres.lettremission', verbose_name='Lettre de Mission')),
            ],
        ),
        migrations.CreateModel(
            name='TaxReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rubrique', models.CharField(max_length=100, verbose_name='Rubrique')),
                ('deduc_reint', models.IntegerField(choices=[(0, 'Réintégration'), (1, 'Déduction')], default=0, verbose_name='Sens')),
                ('nature', models.IntegerField(choices=[(0, 'Courant'), (1, 'Non Courant')], verbose_name='Nature')),
                ('Amount', models.FloatField(default=0, verbose_name='Montant')),
                ('auto_genre', models.BooleanField(default=False, verbose_name='Compte Auto-Généré ?')),
                ('code_account', models.CharField(blank=True, max_length=20, null=True, verbose_name='Code Post / Compte')),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.situation', verbose_name='Exercice')),
            ],
        ),
    ]
