# Generated by Django 3.2.4 on 2021-09-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_account_exercice_situation_taxreturn'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='nature',
            field=models.IntegerField(choices=[(0, 'Courant'), (1, 'Non Courant')], default=0, verbose_name='Nature'),
        ),
        migrations.AlterField(
            model_name='account',
            name='deduc_reint',
            field=models.IntegerField(choices=[(0, 'Réintégration'), (1, 'Déduction')], default=0, verbose_name='Déduction ou Réintégration'),
        ),
        migrations.AlterField(
            model_name='taxreturn',
            name='deduc_reint',
            field=models.IntegerField(choices=[(0, 'Réintégration'), (1, 'Déduction')], default=0, verbose_name='Déduction ou Réintégration'),
        ),
    ]
