# Generated by Django 3.2.4 on 2021-09-21 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_auto_20210921_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='situation',
            old_name='Numbre_month',
            new_name='numbre_month',
        ),
    ]
