# Generated by Django 3.2.4 on 2021-09-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_rename_exercice_taxreturn_situation'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxreturn',
            name='taxreturn',
            field=models.IntegerField(blank=True, choices=[(0, 'Commun'), (1, 'Résultat Fiscal'), (2, 'Imputation Déficites'), (3, 'Déficites Reportables'), (4, 'Déclaration')], default=0, verbose_name='Rubrique Déclaration Fiscal'),
        ),
    ]
