# Generated by Django 3.2.4 on 2021-10-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_taxreturn_taxreturn'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBis',
            fields=[
                ('code_account', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Code')),
                ('name_account', models.CharField(max_length=100, verbose_name='Libellé')),
                ('nature', models.IntegerField(choices=[(0, 'Courant'), (1, 'Non Courant')], default=0, verbose_name='Nature')),
                ('deduc_reint', models.IntegerField(choices=[(0, 'Réintégration'), (1, 'Déduction')], default=0, verbose_name='Déduction ou Réintégration')),
                ('taxreturn', models.IntegerField(blank=True, choices=[(0, 'Commun'), (1, 'Résultat Fiscal'), (2, 'Imputation Déficites'), (3, 'Déficites Reportables'), (4, 'Déclaration')], default=0, verbose_name='Rubrique Déclaration Fiscal')),
                ('exercice', models.IntegerField(choices=[(0, 'Exercice N (en Cours)'), (1, 'Exercice N-1'), (2, 'Exercice N-2'), (3, 'Exercice N-3'), (4, 'Exercice N-4')], default=0, verbose_name='Quel Exercice ?')),
                ('ordre', models.IntegerField(null=True, verbose_name='Ordre')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='ordre',
            field=models.IntegerField(null=True, verbose_name='Ordre'),
        ),
        migrations.AddField(
            model_name='taxreturn',
            name='ordre',
            field=models.IntegerField(null=True, verbose_name='Ordre'),
        ),
    ]
