# Generated by Django 3.2.4 on 2021-10-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_auto_20211001_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxreturn',
            name='deduc_reint',
            field=models.IntegerField(blank=True, choices=[(0, 'Réintégration'), (1, 'Déduction')], null=True, verbose_name='Déduction ou Réintégration'),
        ),
        migrations.AlterField(
            model_name='taxreturn',
            name='nature',
            field=models.IntegerField(blank=True, choices=[(0, 'Courant'), (1, 'Non Courant')], null=True, verbose_name='Nature'),
        ),
    ]
