# Generated by Django 3.2.4 on 2021-10-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_auto_20211001_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='sql_text',
            field=models.TextField(blank=True, null=True, verbose_name='SQL Personalisé'),
        ),
        migrations.AlterField(
            model_name='account',
            name='sql',
            field=models.IntegerField(choices=[(0, 'BETWEEN'), (1, 'LIKE'), (3, 'CUSTUM')], default=0, verbose_name='SQL ?'),
        ),
        migrations.AlterField(
            model_name='account',
            name='taxreturn',
            field=models.IntegerField(blank=True, choices=[(0, 'Commun'), (1, 'Passage au Résultat Fiscal'), (2, 'Imputation Déficites'), (3, 'Déficites Reportables'), (4, 'Résultat Courant Hors Amortissement'), (5, 'Résultat Fiscal'), (6, 'Ventilation du bénéfice net fiscal'), (7, 'Acomptes versés'), (8, 'Calcul Reliquat ou Excédent'), (9, 'Acomptes Provisionnel N+1'), (10, 'Etat Explicatif Déficit ou Résultat Nul'), (11, 'Etat des ventes par client'), (12, 'Etat Entreprises Encouragées'), (13, 'Rubriques base de CM')], default=0, verbose_name='Rubrique Déclaration Fiscal'),
        ),
        migrations.AlterField(
            model_name='accountbis',
            name='taxreturn',
            field=models.IntegerField(blank=True, choices=[(0, 'Commun'), (1, 'Passage au Résultat Fiscal'), (2, 'Imputation Déficites'), (3, 'Déficites Reportables'), (4, 'Résultat Courant Hors Amortissement'), (5, 'Résultat Fiscal'), (6, 'Ventilation du bénéfice net fiscal'), (7, 'Acomptes versés'), (8, 'Calcul Reliquat ou Excédent'), (9, 'Acomptes Provisionnel N+1'), (10, 'Etat Explicatif Déficit ou Résultat Nul'), (11, 'Etat des ventes par client'), (12, 'Etat Entreprises Encouragées'), (13, 'Rubriques base de CM')], default=0, verbose_name='Rubrique Déclaration Fiscal'),
        ),
    ]
