# Generated by Django 3.2.4 on 2021-10-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_auto_20211001_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='situation',
            name='date_exempt_cm',
            field=models.DateField(blank=True, null=True, verbose_name='Date Fin Exonération CM'),
        ),
        migrations.AddField(
            model_name='situation',
            name='date_exempt_is',
            field=models.DateField(blank=True, null=True, verbose_name="Date Fin Exonération d'IS Export"),
        ),
        migrations.AddField(
            model_name='situation',
            name='date_exempt_tp',
            field=models.DateField(blank=True, null=True, verbose_name='Date Fin Exonération TP'),
        ),
        migrations.AddField(
            model_name='situation',
            name='exempt_cm',
            field=models.BooleanField(default=False, verbose_name='Exonération CM'),
        ),
        migrations.AddField(
            model_name='situation',
            name='exempt_is',
            field=models.BooleanField(default=False, verbose_name="Exonération d'IS Export"),
        ),
        migrations.AddField(
            model_name='situation',
            name='exempt_tp',
            field=models.BooleanField(default=False, verbose_name='Exonération TP'),
        ),
        migrations.AlterField(
            model_name='cotisationminimal',
            name='regime',
            field=models.IntegerField(choices=[(0, 'Imposable 100%'), (1, 'Exonération 100%')], default=0, verbose_name='Déduction ou Réintégration'),
        ),
    ]
