# Generated by Django 3.2.4 on 2021-10-23 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_auto_20211012_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotisationminimal',
            name='regime',
            field=models.IntegerField(choices=[(0, 'Imposable 100%'), (1, 'Exonération 100%')], default=0, verbose_name='Imposition ou Exonération'),
        ),
        migrations.AlterField(
            model_name='cotisationminimal',
            name='taux',
            field=models.FloatField(choices=[(0.0045, '0,45%'), (0.005, '0,5%'), (0.006, '0,6%'), (0.0, '0%')], default=0.005, verbose_name='Taux CM'),
        ),
    ]
