# Generated by Django 3.2.4 on 2021-10-23 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_baremeis_impotsociete'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BaremeIS',
            new_name='BaremeImpot',
        ),
    ]
