# Generated by Django 3.2.4 on 2021-11-05 10:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_rename_baremeis_baremeimpot'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableLiasseFiscale',
            fields=[
                ('code_table', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Code Table')),
                ('name_table', models.CharField(max_length=150, verbose_name='Nom de la table')),
                ('text_controle', models.TextField(blank=True, null=True, verbose_name='Description de la Vérification')),
                ('text_sql', models.TextField(blank=True, null=True, verbose_name='SQL Valeur Vérifiée')),
                ('text_sql_X', models.TextField(blank=True, null=True, verbose_name='SQL Valeur de Référence')),
                ('tolerance', models.FloatField(default=0, verbose_name='Seuil de tolérence')),
                ('comparable', models.BooleanField(default=True, verbose_name='Rapprochement de 2 valeurs ?')),
                ('text_KO', models.TextField(blank=True, null=True, verbose_name='Message Echéc')),
                ('text_OK', models.TextField(blank=True, null=True, verbose_name='Message Succès')),
                ('ordre', models.IntegerField(null=True, verbose_name='Ordre')),
            ],
        ),
        migrations.CreateModel(
            name='LiasseFiscale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount_1', models.FloatField(default=0, verbose_name='Valeur de Référence')),
                ('statut', models.IntegerField(choices=[(0, 'En Cours'), (1, 'Traitée'), (2, 'Validée'), (3, 'Non-validée'), (4, 'Non Applicable')], default=0, verbose_name='Statut')),
                ('auto_genre', models.BooleanField(default=False, verbose_name='Compte Auto-Généré ?')),
                ('ordre', models.IntegerField(null=True, verbose_name='Ordre')),
                ('situation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.situation', verbose_name='Exercice')),
                ('tableliassefiscale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.tableliassefiscale', verbose_name='Table Liasse Fiscale')),
            ],
        ),
    ]
