# Generated by Django 3.2.4 on 2021-11-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_liassefiscale_tableliassefiscale'),
    ]

    operations = [
        migrations.AddField(
            model_name='liassefiscale',
            name='amount_2',
            field=models.FloatField(default=0, verbose_name='Valeur de Référence'),
        ),
        migrations.AlterField(
            model_name='liassefiscale',
            name='amount_1',
            field=models.FloatField(default=0, verbose_name='Valeur à Vérifier'),
        ),
    ]
