# Generated by Django 3.2.4 on 2021-11-06 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_liassefiscale_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tableliassefiscale',
            name='comparable',
        ),
        migrations.RemoveField(
            model_name='tableliassefiscale',
            name='text_sql_X',
        ),
    ]
