# Generated by Django 3.2.4 on 2021-11-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0025_das_dasdetail_dasmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='das',
            name='date_closing',
            field=models.DateField(null=True, verbose_name='Date clôture'),
        ),
        migrations.AddField(
            model_name='das',
            name='date_start',
            field=models.DateField(null=True, verbose_name='Date début'),
        ),
    ]
