# Generated by Django 3.2.4 on 2021-11-07 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0028_dasmodel_statut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dasmodel',
            name='statut',
        ),
        migrations.AddField(
            model_name='dasmodel',
            name='type',
            field=models.IntegerField(choices=[(0, 'Bulletin'), (1, 'Etat DAS'), (2, 'Ecritures Comptable')], default=0, verbose_name='Type table'),
        ),
    ]
