# Generated by Django 3.2.4 on 2021-11-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0029_auto_20211107_1745'),
    ]

    operations = [
        migrations.RenameField(
            model_name='das',
            old_name='mois',
            new_name='month',
        ),
        migrations.AddField(
            model_name='exercice',
            name='intermediate',
            field=models.BooleanField(default=False, verbose_name='Situation Intermédiaire ?'),
        ),
        migrations.AddField(
            model_name='exercice',
            name='month',
            field=models.IntegerField(blank=True, choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], default=12, verbose_name="Jusqu'au Mois"),
        ),
        migrations.AlterField(
            model_name='exercice',
            name='exercice',
            field=models.CharField(max_length=4, verbose_name='Exercice'),
        ),
        migrations.AlterUniqueTogether(
            name='exercice',
            unique_together={('exercice', 'month')},
        ),
    ]
