# Generated by Django 3.2.4 on 2021-11-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0030_auto_20211107_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercice',
            name='month',
            field=models.IntegerField(blank=True, choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], null=True, verbose_name="Jusqu'au Mois"),
        ),
    ]
