# Generated by Django 3.2.4 on 2021-11-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0031_alter_exercice_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='dasdetail',
            name='coherence',
            field=models.BooleanField(default=False, verbose_name='Eléments Cohérents ?'),
        ),
    ]
