# Generated by Django 3.2.4 on 2021-11-10 09:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0032_dasdetail_coherence'),
    ]

    operations = [
        migrations.CreateModel(
            name='DASMatriculeDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matricule', models.CharField(max_length=10, null=True, verbose_name='Matrcule')),
                ('sbg', models.FloatField(default=0, verbose_name='SBG')),
                ('exonere', models.FloatField(default=0, verbose_name='Eléments Exonérés')),
                ('sbi', models.FloatField(default=0, verbose_name='SBI')),
                ('fp', models.FloatField(default=0, verbose_name='Frais Professionnels')),
                ('taux_fp', models.FloatField(default=0, verbose_name='Taux FP')),
                ('retenues', models.FloatField(default=0, verbose_name='Retenues')),
                ('deduction', models.FloatField(default=0, verbose_name='Déductions')),
                ('njt', models.FloatField(default=0, verbose_name='Nombre Jours Travaillée')),
                ('imposable_ir', models.BooleanField(default=True, verbose_name="Soumis à l'IR ?")),
                ('taux_fixe_ir', models.FloatField(default=0, verbose_name='Taux Fixe IR')),
                ('ir', models.FloatField(default=0, verbose_name='IR versé')),
                ('ir_reconstitue', models.FloatField(default=0, verbose_name='IR Reconstitué')),
                ('coherence', models.BooleanField(default=False, verbose_name='Eléments Cohérents ?')),
                ('auto_genre', models.BooleanField(default=False, verbose_name='Compte Auto-Généré ?')),
                ('das', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.das', verbose_name='Mois / Exercice')),
            ],
        ),
    ]
