# Generated by Django 3.2.4 on 2021-11-10 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0033_dasmatriculedetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='dasmatriculedetail',
            name='logeco',
            field=models.FloatField(default=0, verbose_name='Logement Eco'),
        ),
        migrations.AddField(
            model_name='dasmatriculedetail',
            name='logneco',
            field=models.FloatField(default=0, verbose_name='Logement Non Eco'),
        ),
        migrations.AddField(
            model_name='dasmatriculedetail',
            name='retcomp',
            field=models.FloatField(default=0, verbose_name='Retraite Complémentaire'),
        ),
    ]
