# Generated by Django 3.2.4 on 2021-11-17 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordres', '0008_alter_lettremissionlink_lettremission'),
        ('tasks', '0034_auto_20211110_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefititem',
            name='benefitlink',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.benefitlink', verbose_name='Lettre de Mission'),
        ),
        migrations.AlterField(
            model_name='benefititem',
            name='code_benefit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.benefit', verbose_name='Particularité'),
        ),
        migrations.AlterField(
            model_name='benefitlink',
            name='lettremission',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ordres.lettremission', verbose_name='Lettre de Mission'),
        ),
        migrations.AlterField(
            model_name='benefitrequested',
            name='worklink',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.work', verbose_name='Référence de la tâche'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='lettremission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ordres.lettremission', verbose_name='Lettre de Mission'),
        ),
        migrations.AlterField(
            model_name='das',
            name='lettremission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ordres.lettremission', verbose_name='Lettre de Mission'),
        ),
        migrations.AlterField(
            model_name='situation',
            name='lettremission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ordres.lettremission', verbose_name='Lettre de Mission'),
        ),
        migrations.AlterField(
            model_name='task',
            name='code_benefit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.benefit', verbose_name='Particularité'),
        ),
        migrations.AlterField(
            model_name='vatrequested',
            name='benefitlink',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.benefitlink', verbose_name='Objet de la demande'),
        ),
        migrations.AlterField(
            model_name='vatrequested',
            name='lettremission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ordres.lettremission', verbose_name='Lettre de Mission'),
        ),
        migrations.AlterField(
            model_name='work',
            name='lettremission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ordres.lettremission', verbose_name='Lettre de Mission'),
        ),
        migrations.AlterField(
            model_name='work',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.task', verbose_name='Job to do'),
        ),
    ]
