# Generated by Django 3.2.4 on 2021-11-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0035_auto_20211117_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='DASEXOModel',
            fields=[
                ('code_rubrique', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Code Rubrique')),
                ('name_rubrique', models.CharField(max_length=150, verbose_name='Nom de la Rubrique')),
                ('type', models.IntegerField(choices=[(0, 'Forfait'), (1, 'Sur Justificatif'), (2, 'Pourcentage')], default=0, verbose_name='Type Rubrique')),
                ('periodicite', models.IntegerField(choices=[(0, 'Mensuelle'), (1, 'Annuelle'), (2, 'Unique')], default=0, verbose_name='Périodicité Rubrique')),
                ('value', models.FloatField(default=0, verbose_name='Valeur')),
                ('ordre', models.IntegerField(null=True, verbose_name='Ordre')),
            ],
        ),
    ]
