# Generated by Django 3.2.4 on 2021-11-19 11:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0036_dasexomodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='DASMatriculeExo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matricule', models.CharField(max_length=10, null=True, verbose_name='Matrcule')),
                ('amount', models.FloatField(default=0, verbose_name='Valeur')),
                ('coherence', models.BooleanField(default=False, verbose_name='Eléments Cohérents ?')),
                ('auto_genre', models.BooleanField(default=False, verbose_name='Compte Auto-Généré ?')),
                ('ordre', models.IntegerField(null=True, verbose_name='Ordre')),
                ('das', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.das', verbose_name='Mois / Exercice')),
                ('dasexomodel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.dasexomodel', verbose_name='Rubrique')),
            ],
        ),
    ]
