# Generated by Django 3.2.4 on 2021-11-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0038_auto_20211119_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dasexomodel',
            name='name_rubrique',
            field=models.CharField(max_length=300, verbose_name='Nom de la Rubrique'),
        ),
    ]
