# Generated by Django 3.2.4 on 2021-11-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0039_alter_dasexomodel_name_rubrique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dasexomodel',
            name='code_rubrique',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Code Rubrique'),
        ),
    ]
