# Generated by Django 3.2.4 on 2021-11-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0041_auto_20211119_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dasmodel',
            name='type',
            field=models.IntegerField(choices=[(0, 'Bulletin'), (1, 'Etat DAS'), (2, 'Ecritures Comptable'), (3, 'Personalisé')], default=0, verbose_name='Type table'),
        ),
    ]
