# Generated by Django 3.2.4 on 2021-11-22 17:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0042_alter_dasmodel_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DASMatriculeFIPP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('matricule', models.CharField(max_length=10, null=True, verbose_name='Matrcule')),
                ('nom', models.CharField(max_length=100, null=True, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, null=True, verbose_name='Prénom')),
                ('adresse', models.CharField(max_length=300, null=True, verbose_name='Adresse')),
                ('ville', models.CharField(max_length=100, null=True, verbose_name='Ville')),
                ('cin', models.CharField(max_length=15, null=True, verbose_name='CIN')),
                ('datenaissance', models.DateField(null=True, verbose_name='Date Naissance')),
                ('sexe', models.IntegerField(blank=True, choices=[(1, 'Homme'), (2, 'Femme')], null=True, verbose_name='Genre')),
                ('nationalite', models.CharField(max_length=300, null=True, verbose_name='Nationalité')),
                ('situationfam', models.CharField(max_length=300, null=True, verbose_name='Situation Familiale')),
                ('deduction', models.CharField(max_length=300, null=True, verbose_name='Nombre Déductions')),
                ('cnss', models.CharField(max_length=300, null=True, verbose_name='Numéro CNSS')),
                ('tauxfp', models.CharField(max_length=300, null=True, verbose_name='Taux FP')),
                ('coherence', models.BooleanField(default=False, verbose_name='Eléments Cohérents ?')),
                ('auto_genre', models.BooleanField(default=False, verbose_name='Compte Auto-Généré ?')),
                ('ordre', models.IntegerField(null=True, verbose_name='Ordre')),
                ('das', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.das', verbose_name='Mois / Exercice')),
            ],
        ),
    ]
