# Generated by Django 3.2.4 on 2021-11-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordres', '0009_auto_20211119_1248'),
        ('tasks', '0043_dasmatriculefipp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercice',
            name='month',
            field=models.IntegerField(choices=[(1, 'Janvier'), (2, 'Février'), (3, 'Mars'), (4, 'Avril'), (5, 'Mai'), (6, 'Juin'), (7, 'Juillet'), (8, 'Août'), (9, 'Septembre'), (10, 'Octobre'), (11, 'Novembre'), (12, 'Décembre')], default=12, null=True, verbose_name="Jusqu'au Mois"),
        ),
        migrations.AlterUniqueTogether(
            name='das',
            unique_together={('exercice', 'lettremission')},
        ),
    ]
