# Generated by Django 3.2.4 on 2021-11-30 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0044_auto_20211127_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='file',
            field=models.FileField(blank=True, upload_to='files/claims/', verbose_name='Joindre une picèe'),
        ),
    ]
