# Generated by Django 3.2.4 on 2021-12-01 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0046_auto_20211201_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='dasmatriculeexo',
            name='commet',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire'),
        ),
    ]
