# Generated by Django 3.2.4 on 2021-12-01 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0047_dasmatriculeexo_commet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dasmatriculeexo',
            old_name='commet',
            new_name='comment',
        ),
    ]
