# Generated by Django 3.2.4 on 2021-12-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0048_rename_commet_dasmatriculeexo_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='dasmatriculedetail',
            name='categorie',
            field=models.IntegerField(choices=[(0, 'Permament'), (1, 'Permanent Exonéré'), (2, 'Stagaire'), (3, 'Occasionnel')], default=0, verbose_name='Catégorie'),
        ),
    ]
