# Generated by Django 3.2.4 on 2021-12-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0049_dasmatriculedetail_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dasmatriculedetail',
            name='categorie',
            field=models.IntegerField(choices=[(1, 'Permament'), (4, 'Permanent Exonéré'), (2, 'Stagaire'), (3, 'Occasionnel')], default=0, verbose_name='Catégorie'),
        ),
    ]
