# Generated by Django 3.2.4 on 2021-12-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0052_dasmatriculecss'),
    ]

    operations = [
        migrations.AddField(
            model_name='dasmatriculecss',
            name='css_regul',
            field=models.FloatField(default=0, verbose_name='Montant Régul CSS'),
        ),
        migrations.AlterField(
            model_name='dasmatriculecss',
            name='matricule',
            field=models.CharField(max_length=10, null=True, verbose_name='Matricule'),
        ),
        migrations.AlterField(
            model_name='dasmatriculedetail',
            name='matricule',
            field=models.CharField(max_length=10, null=True, verbose_name='Matricule'),
        ),
        migrations.AlterField(
            model_name='dasmatriculeexo',
            name='matricule',
            field=models.CharField(max_length=10, null=True, verbose_name='Matricule'),
        ),
        migrations.AlterField(
            model_name='dasmatriculefipp',
            name='matricule',
            field=models.CharField(max_length=10, null=True, verbose_name='Matricule'),
        ),
    ]
