# Generated by Django 3.2.4 on 2021-12-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0053_auto_20211220_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='dasmatriculecss',
            name='categorie',
            field=models.IntegerField(choices=[(1, 'Permament'), (4, 'Permanent Exonéré'), (2, 'Stagaire'), (3, 'Occasionnel')], default=0, verbose_name='Catégorie'),
        ),
    ]
