# Generated by Django 3.2.4 on 2022-04-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0054_dasmatriculecss_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='echeance',
            field=models.DateField(null=True, verbose_name="Date limite d'application"),
        ),
        migrations.AddField(
            model_name='task',
            name='provisoire',
            field=models.BooleanField(default=False, null=True, verbose_name='Limitée dans le temps ?'),
        ),
        migrations.AddField(
            model_name='task',
            name='validator_manager',
            field=models.BooleanField(default=False, null=True, verbose_name='Validateur Manager ?'),
        ),
        migrations.AlterField(
            model_name='baremeimpot',
            name='impot',
            field=models.IntegerField(choices=[(0, 'IS'), (1, 'IR'), (2, 'CSS'), (3, 'CFC'), (4, 'CFC2020')], default=0, verbose_name='Impôt'),
        ),
        migrations.AlterField(
            model_name='situation',
            name='date_exempt_is',
            field=models.DateField(blank=True, null=True, verbose_name="Date Fin Exonération d'IS Export/CFC"),
        ),
        migrations.AlterField(
            model_name='situation',
            name='exempt_is',
            field=models.BooleanField(default=False, verbose_name="Exonération d'IS Export/CFC"),
        ),
    ]
