# Generated by Django 3.2.4 on 2022-04-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0055_auto_20220413_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefititem',
            name='numbre_add',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Nombre à rajouter'),
        ),
    ]
