# Generated by Django 3.2.4 on 2021-07-08 15:46

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moduleservice', models.CharField(max_length=200, unique=True, verbose_name='Nom du Module')),
            ],
        ),
        migrations.CreateModel(
            name='Ordre',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ordre_date', models.DateField(verbose_name='Date de commande')),
                ('comment', models.CharField(max_length=200, null=True, verbose_name='Commentaire')),
                ('statut', models.IntegerField(choices=[(0, 'En Approbation'), (1, 'En Cours'), (2, 'Terminée'), (4, 'Facturée'), (3, 'Annulée')], default=0, verbose_name='Statut')),
                ('file', models.FileField(blank=True, upload_to='files/ordres/', verbose_name='Joindre Devis')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.company', verbose_name='Raison Sociale')),
                ('office', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.office', verbose_name='Cabinet')),
            ],
            options={
                'verbose_name_plural': 'ordres',
            },
        ),
        migrations.CreateModel(
            name='Outlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outlay', models.CharField(max_length=100, unique=True, verbose_name='Débours')),
                ('text', models.CharField(max_length=300, null=True, verbose_name='Désignation du Débours')),
                ('moduleservice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ordres.moduleservice')),
            ],
            options={
                'unique_together': {('moduleservice', 'outlay')},
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=100, unique=True, verbose_name='Service')),
                ('text', models.CharField(max_length=300, null=True, verbose_name='Désignation du Service')),
                ('moduleservice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ordres.moduleservice')),
            ],
            options={
                'unique_together': {('moduleservice', 'service')},
            },
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.FloatField(default=0, null=True, verbose_name='Honoraires HT')),
                ('taxe', models.FloatField(choices=[(0.2, '20%'), (0.14, '14%'), (0.1, '10%'), (0.07, '7%'), (0.0, '0%')], default=0.2, verbose_name='Taux TVA')),
                ('ordre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ordres.ordre', verbose_name='Commande')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ordres.service', verbose_name='Service')),
            ],
        ),
        migrations.CreateModel(
            name='OutlayItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.FloatField(default=0, null=True, verbose_name='Montant Débours')),
                ('ordre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ordres.ordre', verbose_name='Commande')),
                ('outlay', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ordres.outlay', verbose_name='Débours')),
            ],
        ),
        migrations.CreateModel(
            name='LettreMission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='Référence de la LDM')),
                ('db_office', models.CharField(max_length=10, null=True, verbose_name='Code Dossier')),
                ('entry_date', models.DateField(verbose_name="Date d'Entrée")),
                ('terminate', models.BooleanField(default=False, verbose_name='LDM Résiliée ?')),
                ('leave_date', models.DateField(blank=True, null=True, verbose_name='Date de Départ')),
                ('file', models.FileField(blank=True, upload_to='files/ldms/', verbose_name='Joindre LDM')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.company', verbose_name='Raison Sociale')),
                ('moduleservice', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ordres.moduleservice', verbose_name='Abonnée aux Services')),
                ('office', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.office', verbose_name='Cabinet')),
            ],
            options={
                'unique_together': {('office', 'company')},
            },
        ),
    ]
