# Generated by Django 3.2.4 on 2021-08-21 19:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_auto_20210821_2054'),
        ('ordres', '0002_alter_lettremission_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='LettreMissionLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_recrutement', models.DateTimeField(auto_now=True, verbose_name='Date')),
                ('lettremission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ordres.lettremission', verbose_name='Mission')),
                ('prospect', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.prospect', verbose_name='Prospect')),
            ],
            options={
                'unique_together': {('prospect', 'lettremission')},
            },
        ),
    ]
