# Generated by Django 3.2.4 on 2021-08-23 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordres', '0003_lettremissionlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300, null=True, verbose_name='Description du Service')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ordres.service')),
            ],
            options={
                'unique_together': {('text', 'service')},
            },
        ),
    ]
