# Generated by Django 3.2.4 on 2021-08-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordres', '0004_servicedescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceitem',
            name='quantity',
            field=models.FloatField(default=1, null=True, verbose_name='Quantité'),
        ),
    ]
