# Generated by Django 3.2.4 on 2021-09-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordres', '0006_outlayitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='lettremission',
            name='nothosted',
            field=models.BooleanField(default=False, verbose_name='Sans Database ?'),
        ),
    ]
