# Generated by Django 3.2.4 on 2021-11-19 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0014_auto_20211117_1714'),
        ('ordres', '0008_alter_lettremissionlink_lettremission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lettremission',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.company', verbose_name='Raison Sociale'),
        ),
        migrations.AlterField(
            model_name='ordre',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customers.company', verbose_name='Raison Sociale'),
        ),
    ]
